export default {
  // private
  dashboard: "/dashboard",
  overview: "/overview",
  overviewTwo: "/overview/two",
  overviewThree: "/overview/three",
  tickets: "/tickets",
  ideas: "/ideas",
  ideasTwo: "/ideas/two",
  ideasThree: "/ideas/three",
  contacts: "/contacts",
  agents: "/agents",
  // dashboard: '/dashboard',
  // projectManagement: '/projectManagement',
  // projectManagementTwo: '/projectManagement/addProject',
  // projectManagementThree: '/projectManagement/addAffiliation',
  // projectManagementFour: '/projectManagement/viewAllProjects',
  // centerManagement: '/centerManagement',
  // centerManagementTwo: '/centerManagement/addOperationalState',
  // centerManagementThree: '/centerManagement/addCenterDetails',
  // centerManagementFour: '/centerManagement/viewAllCenters',
  // batchManagement: '/batchManagement',
  // batchManagementTwo: '/batchManagement/generateABN',
  // batchManagementThree: '/batchManagement/addBatch',
  // batchManagementFour: '/batchManagement/addPhotos',
  // batchManagementFive: '/batchManagement/dataCorrection',
  // batchManagementSix: '/batchManagement/dataVerification',
  // batchManagementSeven: '/batchManagement/batchPayment',
  // batchManagementEight: '/batchManagement/batchStatusDetails',
  // batchManagementNine: '/batchManagement/assessorDetails',
  // profileManagement: '/profileManagement',

  articles: "/articles",
  settings: "/settings",
  subscription: "/subscription",
  // auth
  login: "/login",
  signup: "/signup",
  forgotPassword: "/forgot_password",
};
