export const affiliationInfo = {
    Affiliated: [
    {title: "NCVT/AICTE", check: false, value: "NCVT/AICTE"},
    {title: "Central State Government University", check: false, value: "Central State Government University"},
    {title: "University recognized by UGC", check: false, value: "University recognized by UGC"},
    {title: "University recognized by DEC of India", check: false, value: "University recognized by DEC of India"},
    {title: "Set up by Central/State Government", check: false, value: "Set up by Central/State Government"},
    {title: "Any Other", check: false, value: "Any Other"},
],
    SSC:[
    {title: "Management & Enterp.", check: false, value: "Management & Enterp."},
    {title: "Chemical", check: false, value: "Chemical"},
    {title: "Paint & Coating", check: false, value: "Paint & Coating"},
    {title: "Textile & Handicraft", check: false, value: "Textile & Handicraft"},
    {title: "Earth moving & Infra", check: false, value: "Earth moving & Infra"},
    {title: "Food Processing", check: false, value: "Food Processing"},
    {title: "Life Science", check: false, value: "Life Science"},
    {title: "Beauty & Wellness", check: false, value: "Beauty & Wellness"},
    {title: "Iron & Steel", check: false, value: "Iron & Steel"},
    {title: "Security", check: false, value: "Security"},
    {title: "Automotive", check: false, value: "Automotive"},
    {title: "Retail Association's", check: false, value: "Retail Association's"},
    {title: "IT-ITeS", check: false, value: "IT-ITeS"},
    {title: "Media & Entertainment", check: false, value: "Media & Entertainment"},
    {title: "Gems & Jewelry", check: false, value: "Gems & Jewelry"},
    {title: "Education", check: false, value: "Education"},
    {title: "Domestic Worker", check: false, value: "Domestic Worker"},
    {title: "Leather", check: false, value: "Leather"},
    {title: "Furniture & Fitting", check: false, value: "Furniture & Fitting"},
    {title: "Sports", check: false, value: "Sports"},
    {title: "Green Jobs", check: false, value: "Green Jobs"},
    {title: "Handicraft & Carpets", check: false, value: "Handicraft & Carpets"},
    {title: "Logistics", check: false, value: "Logistics"},
    {title: "Telecom", check: false, value: "Telecom"},
    {title: "Rubber", check: false, value: "Rubber"},
    {title: "Indian Plumbing", check: false, value: "Indian Plumbing"},
    {title: "Agriculture", check: false, value: "Agriculture"},
    {title: "Capital Goods", check: false, value: "Capital Goods"},
    {title: "Tourism & Hospitality", check: false, value: "Tourism & Hospitality"},
    {title: "Oil & Gas", check: false, value: "Oil & Gas"},
    {title: "Aviation & Aerospace", check: false, value: "Aviation & Aerospace"},
    {title: "BFSI", check: false, value: "BFSI"},
    {title: "SSC for PwD", check: false, value: "SSC for PwD"},
    {title: "Electronics", check: false, value: "Electronics"},
    {title: "Construction", check: false, value: "Construction"},
    {title: "Healthcare", check: false, value: "Healthcare"},
    {title: "Apparel & Furnishing", check: false, value: "Apparel & Furnishing"},
]
}