export const table = [
    {
      title: "Amasy UID",
      type: "text",
      disabled: false,
      value: "-----------------",
    },
    {
      title: "Center ID",
      type: "text",
      disabled: false,
      value: "-----------------",
    },
    {
      title: "Center Name",
      type: "text",
      disabled: false,
      value: "-----------------",
    },
    {
      title: "Scheme",
      type: "text",
      disabled: false,
      value: "-----------------",
    },
    {
      title: "Scheme",
      type: "text",
      disabled: false,
      value: "-----------------",
    },
    {
      title: "Project ID",
      type: "text",
      disabled: false,
      value: "-----------------",
    },
  ];

export const affiliationInfo = {
    Affiliated: [
    {title: "NCVT/AICTE", value: "NCVT/AICTE"},
    {title: "Central State Government University", value: "Central State Government University"},
    {title: "University recognized by UGC", value: "University recognized by UGC"},
    {title: "University recognized by DEC of India", value: "University recognized by DEC of India"},
    {title: "Set up by Central/State Government", value: "Set up by Central/State Government"},
    {title: "Any Other", value: "Any Other"},
],
    SSC:[
    {title: "Management & Enterp.", value: "Management & Enterp."},
    {title: "Chemical", value: "Chemical"},
    {title: "Paint & Coating", value: "Paint & Coating"},
    {title: "Textile & Handicraft", value: "Textile & Handicraft"},
    {title: "Earth moving & Infra", value: "Earth moving & Infra"},
    {title: "Food Processing", value: "Food Processing"},
    {title: "Life Science", value: "Life Science"},
    {title: "Beauty & Wellness", value: "Beauty & Wellness"},
    {title: "Iron & Steel", value: "Iron & Steel"},
    {title: "Security", value: "Security"},
    {title: "Automotive", value: "Automotive"},
    {title: "Retail Association's", value: "Retail Association's"},
    {title: "IT-ITeS", value: "IT-ITeS"},
    {title: "Media & Entertainment", value: "Media & Entertainment"},
    {title: "Gems & Jewelry", value: "Gems & Jewelry"},
    {title: "Education", value: "Education"},
    {title: "Domestic Worker", value: "Domestic Worker"},
    {title: "Leather", value: "Leather"},
    {title: "Furniture & Fitting", value: "Furniture & Fitting"},
    {title: "Sports", value: "Sports"},
    {title: "Green Jobs", value: "Green Jobs"},
    {title: "Handicraft & Carpets", value: "Handicraft & Carpets"},
    {title: "Logistics", value: "Logistics"},
    {title: "Telecom", value: "Telecom"},
    {title: "Rubber", value: "Rubber"},
    {title: "Indian Plumbing", value: "Indian Plumbing"},
    {title: "Agriculture", value: "Agriculture"},
    {title: "Capital Goods", value: "Capital Goods"},
    {title: "Tourism & Hospitality", value: "Tourism & Hospitality"},
    {title: "Oil & Gas", value: "Oil & Gas"},
    {title: "Aviation & Aerospace", value: "Aviation & Aerospace"},
    {title: "BFSI", value: "BFSI"},
    {title: "SSC for PwD", value: "SSC for PwD"},
    {title: "Electronics", value: "Electronics"},
    {title: "Construction", value: "Construction"},
    {title: "Healthcare", value: "Healthcare"},
    {title: "Apparel & Furnishing", value: "Apparel & Furnishing"},
]
}